### PR TITLE
Xsede copy subgrids

### PR DESCRIPTION
**Pull request by petiay**
To minimize supercomputer resources used, this code addition checks if physics model SED grids for a particular filter combination already exist, and if so, copies them directly into the folder of the field which is being fit without submitting a job to the compute nodes to do so (using the copy_subgridX.script).

The code assumes that once there is a set of subgrids for a field with a certain filter combo - say an LMC field observed in F475W and F814W - those are stored in: shared/scylla/mastergrid_LMC_by_filter/F475W_F814W/. The naming of the subgrid files in these _shared/.../by_filter_ folders is irrelevant.

### CODE REVIEW

**Comment by petiay** [comment]
@christinawlindberg + @cmurray-astro, would you please review this code and see if the changes make sense before approving the PR. 
The test consisted of actually running 2 LMC Scylla fields with the updated code and for me all went smoothly. Feel free to just copy this version of run_beast_xsede.py into your XSEDE directory and run the fitting for a field as you normally would (nothing different required on your part). For now there are generated SED subgrids for fields observed with F475W+F814W or F336W+F475W+F814W, so make sure to pick one of those.

**Comment by cmurray-astro** [comment]
thanks, Petia! I'm sorry it's taken so long to review. Christina just pushed a copy of the "original" run_beast_xsede script -- can you update this PR so that we can do a comparison?

**Comment by christinawlindberg** [comment]
I went ahead and added the changes to the version I had, and submitted that as pull request #11. That way it's easier to see what exact changes were made in the script. It might have been possible to do that with this pull request as well, but I'm not sure how simple it would have been.

**Comment by petiay** [comment]
Thanks, @cmurray-astro and @christinawlindberg! I wonder why the changes did not show separately... Perhaps this is since I did everything, including adding the original code, under the same branch, but had separate commits for the changes.
Here are the initial changes:
https://github.com/Scylla-HST/scylla-beast/pull/9/commits/808fd4b062ea3fb89f9154e1b96136fc74bf49c2
and here is the final addition, or rather, rearranging of code:
https://github.com/Scylla-HST/scylla-beast/pull/9/commits/e3f22105e180193c91993829b656e686b424a16b

**Comment by petiay** [comment]
I see there is a merge conflict stemming from usernames:
```
    # set xsede username
<<<<<<< xsede_copy_subgrids
    username = "petiay"
=======
    username = "clindber"
>>>>>>> main
```
Perhaps the best idea is to make the code generic with "username" vs mine or Christina's user names specified.

**Pull request closed without merging**
